# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f0ab564cd0592646eb5e3491a25595e433c1c226a6a5aa0e0e0077f23e78ffbc92901befe467c4c69c047e30deace47f6135a86699f57c6e45ea8c2c1669293

test:
  secret_key_base: 22974d611fc4fb0a48004b8b18d974017190fc1aa35a981a5f61d47beb59a9f32449e052c34955cea8d15fc0e068caefaefd8c4ba949f5d5909342aa14b3d151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
